In [44]:
import requests as req
import time

In [107]:
url='https://datos.madrid.es/egob/catalogo/209548-2083589-censo-locales-historico.{json}'

# https://datos.madrid.es/egob/catalogo/209548-2083609-censo-locales-historico.{responseContentType}?fecha_dato=2023&desc_situacion_local=activo

#https://datos.comunidad.madrid/catalogo/api/3/action/datastore_search?resource_id=8423a948-3082-465e-b3f8-c13333e8969b&q=jones

In [108]:
res=req.get(url)

In [1]:
%pip install folium

Requirement already satisfied: folium in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (0.14.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from folium) (0.6.0)
Requirement already satisfied: jinja2>=2.9 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from folium) (1.26.1)
Requirement already satisfied: requests in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from folium) (2.31.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from requests->folium) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from requests->folium) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\usuario\anaconda3\envs\clase\lib\site-packages (from requests->folium) (2023.7.22)
Note: you may need to restart the kernel to use updated packages.

In [110]:
res.json().keys()

dict_keys(['page', 'pageSize', 'totalRecords', 'pageRecords', 'status', 'responseDate', 'first', 'last', 'self', 'contentMD5', 'records'])

In [113]:
lista=res.json()['records']

In [124]:
import pandas as pd

df = pd.DataFrame(lista)
df

,id,id_distrito_local,distrito_local,id_barrio_local,desc_barrio_local,id_ndp_edificio,id_clase_ndp_edificio,id_vial_edificio,clase_vial_edificio,desc_vial_edificio,...,nombre_agrupacion,id_tipo_agrup,desc_tipo_agrupacion,fecha_dato,ref_licencia,id_epigrafe,cod_postal,fx_datos_ini,fx_datos_fin,id_terraza
0,20001000,2,ARGANZUELA,205,DELICIAS,20136166,1,88910674,CALLE,MENDEZ ALVARO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,500/2015/03206,561001,28045,2022-05-01,2022-05-01,NaN
1,20001000,2,ARGANZUELA,205,DELICIAS,20136166,1,88910674,CALLE,MENDEZ ALVARO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,102/2002/06641,561001,28045,2022-05-01,2022-05-01,NaN
2,20001000,2,ARGANZUELA,205,DELICIAS,20136166,1,88910674,CALLE,MENDEZ ALVARO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,220/2013/15009,561001,28045,2022-05-01,2022-05-01,NaN
3,20001000,2,ARGANZUELA,205,DELICIAS,20136166,1,88910674,CALLE,MENDEZ ALVARO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,500/2018/07937,561001,28045,2022-05-01,2022-05-01,NaN
4,20001000,2,ARGANZUELA,205,DELICIAS,20136166,1,88910674,CALLE,MENDEZ ALVARO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,500/2019/02966,561001,28045,2022-05-01,2022-05-01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10000004,1,CENTRO,105,UNIVERSIDAD,11006452,1,4700,CALLE,ACUERDO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,350/2021/02524,561006,28015,2022-05-01,2022-05-01,19621.0
96,10000004,1,CENTRO,105,UNIVERSIDAD,11006452,1,4700,CALLE,ACUERDO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,350/2021/02524,561006,28015,2022-05-01,2022-05-01,19621.0
97,10000004,1,CENTRO,105,UNIVERSIDAD,11006452,1,4700,CALLE,ACUERDO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,350/2021/02524,561006,28015,2022-05-01,2022-05-01,19621.0
98,10000004,1,CENTRO,105,UNIVERSIDAD,11006452,1,4700,CALLE,ACUERDO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,350/2021/02524,561006,28015,2022-05-01,2022-05-01,19621.0
99,10000004,1,CENTRO,105,UNIVERSIDAD,11006452,1,4700,CALLE,ACUERDO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,350/2021/02524,561006,28015,2022-05-01,2022-05-01,19621.0

In [130]:
df = df.drop_duplicates(subset='id')
df

,id,id_distrito_local,distrito_local,id_barrio_local,desc_barrio_local,id_ndp_edificio,id_clase_ndp_edificio,id_vial_edificio,clase_vial_edificio,desc_vial_edificio,...,nombre_agrupacion,id_tipo_agrup,desc_tipo_agrupacion,fecha_dato,ref_licencia,id_epigrafe,cod_postal,fx_datos_ini,fx_datos_fin,id_terraza
0,20001000,2,ARGANZUELA,205,DELICIAS,20136166,1,88910674,CALLE,MENDEZ ALVARO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,500/2015/03206,561001,28045,2022-05-01,2022-05-01,NaN
40,10000004,1,CENTRO,105,UNIVERSIDAD,11006452,1,4700,CALLE,ACUERDO ...,...,SIN AGRUPACION,-1,SIN AGRUPACION,2022-05-19T09:08:24,350/2021/02524,561006,28015,2022-05-01,2022-05-01,19621.0